In [1]:
import pandas as pd

In [2]:
la_df = pd.read_csv("./la_listings.csv")
ny_df = pd.read_csv("./ny_listings.csv")
la_df["state"] = "LA"
ny_df["state"] = "NY"

df_list = [la_df, ny_df]

/var/folders/h8/sxlsbms534sc8_ln9tk771tr0000gn/T/ipykernel_26247/1218132431.py:2: DtypeWarning: Columns (68) have mixed types. Specify dtype option on import or set low_memory=False.
  ny_df = pd.read_csv("./ny_listings.csv")

In [3]:
all_df = pd.concat(df_list, axis=0)
all_df

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,state
0,183319,https://www.airbnb.com/rooms/183319,20220909140055,2022-09-10,previous scrape,Panoramic Ocean View Venice Beach,Craftsmen style penthouse with ocean view from...,About as close to the beach as you can live in...,https://a0.muscache.com/pictures/1170205/e2596...,867995,...,5.00,5.00,NaN,f,2,2,0,0,0.02,LA
1,51307,https://www.airbnb.com/rooms/51307,20220909140055,2022-09-10,city scrape,Spanish Bungalow Guest House LA CA. 30 plus ni...,PRIVATE GUEST HOUSE<br /><br /><b>The space</b...,"Local LA Community , shops and restaurants in...",https://a0.muscache.com/pictures/294658/ac8d6e...,235568,...,4.95,4.76,NaN,f,2,2,0,0,0.98,LA
2,184314,https://www.airbnb.com/rooms/184314,20220909140055,2022-09-10,previous scrape,Boho Chic Flat..Steps to Beach!,"Bright, airy, quiet 1 bdr located just steps f...",You are in one of the beach locations in Los A...,https://a0.muscache.com/pictures/0bc2f8b7-9378...,884031,...,4.89,4.85,NaN,t,1,1,0,0,0.22,LA
3,51498,https://www.airbnb.com/rooms/51498,20220909140055,2022-09-10,city scrape,Guest House With Its Own Entrance/Exit and Hot...,"Fully self-contained, separate structure, with...",We are close to Venice without the hassle of n...,https://a0.muscache.com/pictures/83426633/c9e3...,236758,...,4.83,4.74,HSR19-001336,f,1,1,0,0,2.60,LA
4,109,https://www.airbnb.com/rooms/109,20220909140055,2022-09-10,city scrape,Amazing bright elegant condo park front *UPGRA...,"*** Unit upgraded with new bamboo flooring, br...",NaN,https://a0.muscache.com/pictures/4321499/1da98...,521,...,5.00,4.00,NaN,f,1,1,0,0,0.01,LA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39876,43728504,https://www.airbnb.com/rooms/43728504,20220907064715,2022-09-08,previous scrape,Private Modern House by The Beach,Private modern house by the Beach with all com...,Rockaway Beach is a neighborhood that gives it...,https://a0.muscache.com/pictures/6c950656-b090...,23049030,...,4.94,4.88,NaN,f,1,1,0,0,1.22,NY
39877,44578886,https://www.airbnb.com/rooms/44578886,20220907064715,2022-09-08,previous scrape,Beautiful apartment - minutes to NYC,Our apartment is straight across the river fro...,Our apartment is located in a very interesting...,https://a0.muscache.com/pictures/dd5163c1-7e02...,48009648,...,4.81,4.85,NaN,f,1,1,0,0,2.12,NY
39878,46355090,https://www.airbnb.com/rooms/46355090,20220907064715,2022-09-08,previous scrape,"1 Bedroom Basement, NEWLY Renovated",With easy access to multiple bus stops and the...,NaN,https://a0.muscache.com/pictures/64c81ee7-b396...,371552251,...,4.36,4.55,NaN,t,1,1,0,0,0.50,NY
39879,698195550745703156,https://www.airbnb.com/rooms/698195550745703156,20220907064715,2022-09-08,city scrape,"Luxurious private waterfront terrace, 2BR 2BA Apt","This two bed, two bath apartment overlooking t...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,151487807,...,NaN,NaN,NaN,f,1,1,0,0,NaN,NY
39880,48971505,https://www.airbnb.com/rooms/48971505,20220907064715,2022-09-08,previous scrape,Just Blocks to Grove PATH and JC Med Ctr,Very convenient to the Grove St PATH (5 min wa...,NaN,https://a0.muscache.com/pictures/b12bc7dc-573c...,46201,...,4.87,4.47,NaN,f,1,0,1,0,0.91,NY

In [4]:
all_df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month',
       'state'],
      dtype='object')

In [5]:
f = open("./untitled.txt")
lines = f.readlines()

temp_list = []
for line in lines:
    if line == lines[-1]:
        temp_list.append(line)
    else:
        temp_list.append(line[:-1])
    
temp_list

['host_response_time',
 'host_response_rate',
 'host_is_superhost',
 'host_listings_count',
 'host_has_profile_pic',
 'host_identity_verified',
 'state',
 'is_location_exact',
 'property_type',
 'room_type',
 'accommodates',
 'bedrooms',
 'beds',
 'minimum_nights',
 'maximum_nights',
 'number_of_reviews',
 'review_scores_rating',
 'price',
 'latitude',
 'longitude',
 'state']

In [6]:
new_list = [i for i in temp_list if i in list(all_df.columns)]

In [7]:
new_list

['host_response_time',
 'host_response_rate',
 'host_is_superhost',
 'host_listings_count',
 'host_has_profile_pic',
 'host_identity_verified',
 'state',
 'property_type',
 'room_type',
 'accommodates',
 'bedrooms',
 'beds',
 'minimum_nights',
 'maximum_nights',
 'number_of_reviews',
 'review_scores_rating',
 'price',
 'latitude',
 'longitude',
 'state']

In [8]:
all_df = all_df.loc[:, new_list]
all_df

,host_response_time,host_response_rate,host_is_superhost,host_listings_count,host_has_profile_pic,host_identity_verified,state,property_type,room_type,accommodates,bedrooms,beds,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,price,latitude,longitude,state
0,within a day,100%,f,2.0,t,f,LA,Entire rental unit,Entire home/apt,2,2.0,2.0,30,90,3,5.00,$152.00,33.992110,-118.476000,LA
1,NaN,NaN,f,2.0,t,t,LA,Entire bungalow,Entire home/apt,2,1.0,1.0,30,365,138,4.64,$75.00,34.122060,-118.267830,LA
2,NaN,NaN,f,2.0,t,t,LA,Entire rental unit,Entire home/apt,1,1.0,1.0,30,30,30,4.88,$125.00,33.974870,-118.463120,LA
3,within an hour,100%,f,1.0,t,t,LA,Entire guesthouse,Entire home/apt,2,NaN,1.0,3,365,378,4.73,$189.00,34.003890,-118.441260,LA
4,NaN,NaN,f,1.0,t,t,LA,Entire condo,Entire home/apt,6,2.0,3.0,30,730,2,4.00,$115.00,33.983010,-118.386070,LA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39876,within an hour,100%,f,5.0,t,t,NY,Entire home,Entire home/apt,2,1.0,1.0,3,7,33,4.91,$157.00,40.581060,-73.829850,NY
39877,within an hour,100%,t,1.0,t,t,NY,Entire rental unit,Entire home/apt,4,1.0,2.0,3,1125,52,4.79,$108.00,40.784590,-74.012530,NY
39878,within an hour,100%,f,1.0,t,t,NY,Entire rental unit,Entire home/apt,2,1.0,2.0,3,30,11,4.45,$140.00,40.723410,-73.722350,NY
39879,NaN,NaN,f,1.0,t,t,NY,Entire rental unit,Entire home/apt,4,2.0,2.0,30,365,0,NaN,$400.00,40.709192,-73.970121,NY
39880,within a few hours,100%,f,3.0,t,t,NY,Private room in rental unit,Private room,1,1.0,NaN,1,1125,15,4.47,$40.00,40.718350,-74.044160,NY

In [9]:
all_df = all_df.dropna()
all_df

,host_response_time,host_response_rate,host_is_superhost,host_listings_count,host_has_profile_pic,host_identity_verified,state,property_type,room_type,accommodates,bedrooms,beds,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,price,latitude,longitude,state
0,within a day,100%,f,2.0,t,f,LA,Entire rental unit,Entire home/apt,2,2.0,2.0,30,90,3,5.00,$152.00,33.992110,-118.476000,LA
5,within a few hours,100%,f,2.0,t,t,LA,Private room in home,Private room,1,1.0,1.0,30,730,13,4.42,$85.00,33.961540,-118.423730,LA
6,within an hour,100%,t,2.0,t,t,LA,Private room in rental unit,Private room,1,1.0,1.0,30,550,37,4.84,$93.00,34.096250,-118.346050,LA
7,within a few hours,100%,t,1.0,t,t,LA,Entire rental unit,Entire home/apt,6,1.0,2.0,31,365,188,4.92,$100.00,34.118740,-118.321130,LA
8,within a few hours,100%,f,2.0,t,t,LA,Private room in home,Private room,1,1.0,1.0,30,730,12,4.92,$85.00,33.962000,-118.422040,LA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39871,within an hour,100%,f,1.0,t,t,NY,Private room in guest suite,Private room,2,2.0,3.0,27,30,6,5.00,$125.00,40.702410,-73.724930,NY
39873,a few days or more,46%,f,5.0,t,t,NY,Private room in rental unit,Private room,6,2.0,2.0,1,1125,3,5.00,$150.00,40.739967,-74.031677,NY
39876,within an hour,100%,f,5.0,t,t,NY,Entire home,Entire home/apt,2,1.0,1.0,3,7,33,4.91,$157.00,40.581060,-73.829850,NY
39877,within an hour,100%,t,1.0,t,t,NY,Entire rental unit,Entire home/apt,4,1.0,2.0,3,1125,52,4.79,$108.00,40.784590,-74.012530,NY
39878,within an hour,100%,f,1.0,t,t,NY,Entire rental unit,Entire home/apt,2,1.0,2.0,3,30,11,4.45,$140.00,40.723410,-73.722350,NY

In [10]:
all_df["host_response_rate"] = all_df["host_response_rate"].apply(lambda x: int(x[:-1]))
all_df["price"] = all_df["price"].apply(lambda x: (x[1:-3]).replace(",", ""))
all_df

/var/folders/h8/sxlsbms534sc8_ln9tk771tr0000gn/T/ipykernel_26247/885954420.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_df["host_response_rate"] = all_df["host_response_rate"].apply(lambda x: int(x[:-1]))
/var/folders/h8/sxlsbms534sc8_ln9tk771tr0000gn/T/ipykernel_26247/885954420.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_df["price"] = all_df["price"].apply(lambda x: (x[1:-3]).replace(",", ""))

,host_response_time,host_response_rate,host_is_superhost,host_listings_count,host_has_profile_pic,host_identity_verified,state,property_type,room_type,accommodates,bedrooms,beds,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,price,latitude,longitude,state
0,within a day,100,f,2.0,t,f,LA,Entire rental unit,Entire home/apt,2,2.0,2.0,30,90,3,5.00,152,33.992110,-118.476000,LA
5,within a few hours,100,f,2.0,t,t,LA,Private room in home,Private room,1,1.0,1.0,30,730,13,4.42,85,33.961540,-118.423730,LA
6,within an hour,100,t,2.0,t,t,LA,Private room in rental unit,Private room,1,1.0,1.0,30,550,37,4.84,93,34.096250,-118.346050,LA
7,within a few hours,100,t,1.0,t,t,LA,Entire rental unit,Entire home/apt,6,1.0,2.0,31,365,188,4.92,100,34.118740,-118.321130,LA
8,within a few hours,100,f,2.0,t,t,LA,Private room in home,Private room,1,1.0,1.0,30,730,12,4.92,85,33.962000,-118.422040,LA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39871,within an hour,100,f,1.0,t,t,NY,Private room in guest suite,Private room,2,2.0,3.0,27,30,6,5.00,125,40.702410,-73.724930,NY
39873,a few days or more,46,f,5.0,t,t,NY,Private room in rental unit,Private room,6,2.0,2.0,1,1125,3,5.00,150,40.739967,-74.031677,NY
39876,within an hour,100,f,5.0,t,t,NY,Entire home,Entire home/apt,2,1.0,1.0,3,7,33,4.91,157,40.581060,-73.829850,NY
39877,within an hour,100,t,1.0,t,t,NY,Entire rental unit,Entire home/apt,4,1.0,2.0,3,1125,52,4.79,108,40.784590,-74.012530,NY
39878,within an hour,100,f,1.0,t,t,NY,Entire rental unit,Entire home/apt,2,1.0,2.0,3,30,11,4.45,140,40.723410,-73.722350,NY

In [11]:
all_df.to_csv("./preprocessing_dataframe.csv")